# $Id: Makefile,v 1.3 2002/06/03 20:09:42 mori Exp $
#  Linux Kernel Hardening Module
#

CC = gcc

CFLAGS = -O3 -Wall

OBJS = gksmadm.c 

all:	
	$(CC) -o gksmadm $(OBJS) 


clean:
	rm -f *.o
	rm -f gksmadm

